#
# Copyright (c) 2023-present Didier Malenfant
#
# This file is part of openFPGA-Tutorials.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

[Platform]
name = "01 BasicTemplate"
image = "../../assets/platform-image.png"
short_name = "fpgatut01"
category = "Tutorials"
description = "Part of the openFPGA tutorials collection of code samples."
info = "assets/info.txt"

[Build]
version = "0.0.2"

[Author]
name = "dm"
icon = "../../assets/core-author-icon.png"
url = "https://codeberg.org/DidierMalenfant/openFPGA-tutorials"

[Hardware]
video_width = 320
video_height = 240
